### ISSUE TITLE
[Service Request] ProxiTok

### ISSUE THREAD

**Issue by NoPlagiarism** [benbusby/farside#100]
Alternative to TikTok. 

- [GitHub repository](https://github.com/pablouser1/ProxiTok)
- [Wiki page with instances](https://github.com/pablouser1/ProxiTok/wiki/Public-instances)
    - raw link: `https://raw.githubusercontent.com/wiki/pablouser1/ProxiTok/Public-instances.md`

**Comment by benbusby** [comment]
ProxiTok has actually been supported for a while, but I updated the instance list using the latest ones from their wiki.
