### ISSUE TITLE
Simple-Web.org is responding now!

### ISSUE THREAD

**Issue by NoPlagiarism** [benbusby/farside#101]
They moved to new hosting, I guess.

But it's working now!

**Comment by benbusby** [comment]
Hmmm, I'm still not getting a response. I get an SSL error for https://simple-web.org, and an empty response body from http.

**Comment by NoPlagiarism** [comment]
Strange...
![image](https://github.com/benbusby/farside/assets/37241775/95212032-b82d-4bcf-ae2b-d2a5181447a0)

Okay, in case of something.. There CodeBerg repository, including [this config.json](https://codeberg.org/SimpleWeb/Website/src/branch/master/config.json)

raw: `https://codeberg.org/SimpleWeb/Website/raw/branch/master/config.json`

**Comment by NoPlagiarism** [comment]
So... For simplytranslate clearnet instances it will be: `jq '.projects | map(select(.id == "simplytranslate"))[0].instances'`

**Comment by benbusby** [comment]
Cool, thanks for pointing me to their repo. For some reason I thought they were using Sourcehut and not Codeberg...

**Comment by NoPlagiarism** [comment]
Yeah, they **were**
