### ISSUE TITLE
Update instance list for Libremdb

### ISSUE THREAD

**Issue by MintMain21** [benbusby/farside#103]
There are now more instances of Libremdb with advanced search features and paths that I think deserve to be included in Farside. Listed below are the ones I think would be most useful.

libremdb.fascinated.cc

libremdb.iket.me

libremdb.esmailelbob.xyz

ld.vern.cc

binge.whatever.social

libremdb.lunar.icu

lmdb.hostux.net

binge.whateveritworks.org

libremdb.nerdyfam.tech

Additionally, I feel like the instance lmdb.tokhmi.xyz should be dropped until it adopts the more advanced search and path options of the above instances.

**Comment by benbusby** [comment]
Updated, thanks!
