### ISSUE TITLE
Suggestion: Add imgur alternatives

### ISSUE THREAD

**Issue by accountForIssues** [benbusby/farside#11]
Hi, thanks for your work on this app.
I suggest adding imgur alts as well.

(rimgo seems to be support more features like galleries/videos)

## [imgin](https://git.voidnet.tech/kev/imgin/)
- https://imgin.voidnet.tech
## [rimgo](https://codeberg.org/video-prize-ranch/rimgo)
- https://i.bcow.xyz
- https://rimgo.pussthecat.org
- https://img.riverside.rocks
- https://rimgo.totaldarkness.net
- https://rimgo.bus-hit.me

**Comment by benbusby** [comment]
Thanks! I've added both, but am going to hold off on promoting imgin support in the readme until they have more instances.

**Comment by ltGuillaume** [comment]
Plus, the development hasn't been very active for the last months. @accountForIssues Thanks for mentioning Rimgo, I wasn't aware of this project yet. It seems to be further _and_ more active developed than Imgin.
