### ISSUE TITLE
please remove whoogle.link

### ISSUE THREAD

**Issue by bingoxo** [benbusby/farside#111]
if you use [whoogle.link](https://whoogle.link/) it redirects you to https://ftw.lol/services/#whoogle saying
"The Server is already rate limited. Nothing I can do about that. You have to wait until it works again, or just use another public instance."

but their instance https://whoogle.ftw.lol/ works fine

**Comment by benbusby** [comment]
Fixed in https://github.com/benbusby/whoogle-search/commit/421a8ac05455877cbcd9fec335c18598d9b5e885
