### ISSUE TITLE
Check for rate limited Quetre instance

### ISSUE THREAD

**Issue by specter78** [benbusby/farside#117]
quetre.iket.me is presently giving 503 error as Quora is rate limiting this instance.

**Comment by benbusby** [comment]
I'm able to view posts using that instance, so it seems to be back up. 

Farside's polling period is every 5 minutes, and it's occasionally an instance will get rate limited before the next polling period. I could make the polling more frequent, but then that puts instances at a greater risk of getting rate limited by Farside requests.
