### ISSUE TITLE
Add WhateverItWorks Instances

### ISSUE THREAD

**Issue by xbdmHQ** [benbusby/farside#118]
https://whateveritworks.org

**Comment by NoPlagiarism** [comment]
There are already 8 instances in [`services-full.json`](https://github.com/benbusby/farside/blob/main/services-full.json)

Some of them scraped automatically from official lists

**Comment by xbdmHQ** [comment]
> There are already 8 instances in [`services-full.json`](https://github.com/benbusby/farside/blob/main/services-full.json)
> 
> Some of them scraped automatically from official lists

one of them is ```cringe.whateveritworks.social``` which is wrong, should be ```cringe.whateveritworks.org```

**Comment by NoPlagiarism** [comment]
> one of them is cringe.whateveritworks.social

No, it's not. It's just `cringe.whatever.social`, and `cringe.whateveritworks.org` have been added on #110
