### ISSUE TITLE
Update the list of Invidious instances

### ISSUE THREAD

**Issue by TheFrenchGhosty** [benbusby/farside#12]
Hi, Invidious project manager here :)

Can you please update the list of Invidious instances, or ideally, automate its update using https://api.invidious.io/ in the same way you're doing it for SearX and Whoogle.

Thank you

**Comment by benbusby** [comment]
Done -- thanks!

**Comment by TheFrenchGhosty** [comment]
Well, that was fast! Thanks

I just noticed that you were the Whoogle developer (I discovered farside because someone linked to it), good job!
