### ISSUE TITLE
twitter redirect biased to nitter.net

### ISSUE THREAD

**Issue by 1268** [benbusby/farside#126]
I did this 9 times and got this 8 times:

~~~
> curl -I -A iPad https://farside.link/twitter.com/mikko/status/1692503249595584526
HTTP/1.1 302 Found
location: https://nitter.net/mikko/status/1692503249595584526
~~~

and this once:

~~~
> curl -I -A iPad https://farside.link/twitter.com/mikko/status/1692503249595584526
HTTP/1.1 302 Found
location: https://nitter.it/mikko/status/1692503249595584526
~~~

at this point I might as well use nitter.net directly.

**Comment by benbusby** [comment]
It's not biased, it just so happens that nitter.net is typically the first to roll out fixes to its scraping algorithm, and seems to have fewer issues than other instances. Although, running your same test didn't return nitter.net for me at any point. There isn't any code to prefer one instance over another though, it just selects a random one from a pool of working instances and then prefers that instance for a short period of time afterwards.
