### ISSUE TITLE
Remove Reddit because it does not work anymore

### ISSUE THREAD

**Issue by tio-trom** [benbusby/farside#135]
Both Libredit https://github.com/libreddit/libreddit#%EF%B8%8F-why-do-i-get-too-many-requests-errors-%EF%B8%8F and Teddit https://codeberg.org/teddit/teddit#teddit-is-no-more-actively-maintained are not maintained anymore. Reddit's API change killed these services.

**Comment by 11257896** [comment]
@benbusby Do not remove and display a message "looking for a project"

**Comment by sigaloid** [comment]
Superseded by #148

**Comment by benbusby** [comment]
Should be fixed by #148
