### ISSUE TITLE
Doesn't work with x.com URLs

### ISSUE THREAD

**Issue by Antsy4904** [benbusby/farside#136]
This URL doesn't redirect: https://farside.link/https://x.com/x

Sidenote: Is there any chance it could strip URL parameter tracking stuff or should that be a separate issue? Youtube and Twitter has them.  

example: https://farside.link/https://x.com/x?s=46&t=asdf & https://farside.link/https://youtu.be/dQw4w9WgXcQ?si=asdf

**Comment by benbusby** [comment]
Thanks for reporting, x.com links now redirect to nitter instances.

Regarding URL params, that's not something Farside should be handling. They're typically ignored anyways by whichever service you're being forwarded to, at least from what I've seen. Adding rules for which params to strip per service would be unnecessary additional steps for Farside.
