### ISSUE TITLE
Add catsarch.com instances

### ISSUE THREAD

**Issue by ButteredCats** [benbusby/farside#138]
Hi!

Sorry if this isn't the right place for this, I did see the instruction to edit services-full.json but I don't use Github for much so I'm slightly lost on what to do there (and if I should be doing something like a pull request for that?) so I figured I'd just ask here instead of guessing and/or creating needless requests.

Currently my Nitter and BreezeWiki instances show up (https://nitter.catsarch.com, https://breezewiki.catsarch.com) but I was wondering if my other hosted instances could be added:
Rimgo: https://rimgo.catsarch.com
Quetre: https://quetre.catsarch.com
libremdb: https://libremdb.catsarch.com

**Comment by benbusby** [comment]
Thanks for letting me know about these, I just added them!
