### ISSUE TITLE
Add frontendfriendly.xyz instances

### ISSUE THREAD

**Issue by toyboatcash** [benbusby/farside#139]
Currently, my [Lingva](https://lingva.frontendfriendly.xyz/) and [BreezeWiki](https://breezewiki.frontendfriendly.xyz/) and [Gothub](https://gothub.frontendfriendly.xyz/) instances show up, but I was wondering if my other hosted instances could be added:
[Rimgo](https://rimgo.frontendfriendly.xyz/)
[libremdb](https://libremdb.frontendfriendly.xyz/)
[libmedium](https://libmedium.frontendfriendly.xyz/)
[Intellectual](https://intellectual.frontendfriendly.xyz/)
[Invidious](https://invidious.frontendfriendly.xyz/)
[Hyperpipe](https://hyperpipe.frontendfriendly.xyz/)
[Quetre](https://quetre.frontendfriendly.xyz/)
[libreddit](https://libreddit.frontendfriendly.xyz/)
[AnonymousOverflow](https://anonoverflow.frontendfriendly.xyz/)

**Comment by benbusby** [comment]
You can edit https://github.com/benbusby/farside/blob/main/services-full.json to include your instance -- just add an entry to the end of each service section and open a PR

**Comment by benbusby** [comment]
Closed by #143
