### ISSUE TITLE
Would you kindly identify yourself by User-Agent?

### ISSUE THREAD

**Issue by austinhuang0131** [benbusby/farside#14]
Since your current one is

https://github.com/benbusby/farside/blob/932f3bbcab9be82aafb487d7890fde83b2210a7b/config/config.exs#L14

I blocked your IP because I thought you're scraping the service...

I'd suggest something like

```
Mozilla/5.0 (compatible; Farside/0.1.0; +https://farside.link)
```

**Comment by benbusby** [comment]
Updated -- thanks for the suggestion!
