### ISSUE TITLE
I get absolutely bombarded on my 4get instance from requests with farside.link as referrer

### ISSUE THREAD

**Issue by HBubli** [benbusby/farside#147]
I constantly get requests to my server on 4get.hbubli.cc with the referrer being for example “ https://farside.link/4get/web?s=dentist%20los%20angeles&scraper=wiby”. Its a different ip each time, and the user agent seems normal. What is this? Ive blocked all requests with unknown referrers for now with a 444 code, but the requests dont stop. Also the searches inside the url dont make any sense at all.

**Comment by benbusby** [comment]
It kinda sounds like someone is/was using farside as a scraper and probably has multiple servers running random searches constantly. I've adjusted the ratelimiting that Farside performs to block this type of behavior by limiting to 1 request per second (previously it would just send users to the instance that Farside had most recently selected for whichever service was requested). Hopefully that's enough of a deterrent. Sorry you were having to deal with this.

**Comment by HBubli** [comment]
Thanks 👍, it seems to be normal now. Ive unblocked those requests again.
