### ISSUE TITLE
Libreddit update

### ISSUE THREAD

**Issue by sigaloid** [benbusby/farside#148]
Hi, 

I'm a Libreddit maintainer and the original repo has largely stalled. I forked it due to a lack of maintenance and added a fix for the too many requests error and so it would probably be best to transition to Redlib instances (once there is any!). This is kind of a placeholder until we get a good amount of instances. 

https://github.com/redlib-org/redlib

**Comment by sigaloid** [comment]
I'm not sure how much should be changed with regards to the URLs (I think leaving libreddit as the URL slug or leaving it as an option alongside "redlib" would be good) but the main change would be changing this line: https://github.com/benbusby/farside/blob/09a9b00ca9f191c57a1146007d9e0c5c8e43eb66/.github/workflows/update-instances.yml#L202

The new URL is "https://raw.githubusercontent.com/redlib-org/redlib-instances/main/instances.json". There's a handful of instances there but those are more likely to work versus the Libreddit instances are iffy when it comes to rate limits

**Comment by benbusby** [comment]
OK, I think I've made all of the necessary changes for switching to redlib. The auto updater pulls instances from the redlib link you provided, and libreddit URLs will link to redlib instances now. Thank you!

**Comment by sigaloid** [comment]
Thanks!
