### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by lehmanator** [benbusby/farside#154]
Current version of Farside (`v0.2.1`) is from June of 2022, and plenty of commits have happened since.

I'm currently working on packaging Farside in Nix and making a NixOS module to configure and run it. `nixpkgs` wants each package to specify a version number, and I'd like to use a more up-to-date version than `v0.2.1`, but don't want to create a version that mismatches the upstream.

My work is currently based on the `main` branch and has the package revision set to the latest revision. I have the version set as `0.2.2`, but I'd prefer to match the upstream version.

Can we have a new release so I can include some of the features in commits since `v0.2.1`?

I am not familiar with the Elixir ecosystem, but I'm willing to help out in whatever capacity I can in order to make this happen.

Thanks in advance!

**Comment by benbusby** [comment]
Sorry for the delay! I just released `v0.2.2` -- I'll get in a better routine of releasing new versions when notable changes have been made.
