### ISSUE TITLE
Usually, farside.link/nitter/<user> gives "Instance has been rate limited. Use another instance or try again later." Is this a known issue for everyone or just me?

### ISSUE THREAD

**Issue by gth001** [benbusby/farside#155]
It forwards to a random domain each time, but I was under the impression it was supposed to only choose working links, based on the repo readme. About 70% of the domains it forwards to me are rate limited (broken). Am I misunderstanding?

**Comment by benbusby** [comment]
You're not misunderstanding, but Nitter instances in particular seem particularly susceptible to rate limiting. Farside's query for working instances occurs every 5 minutes, but an instance can go from working->not working in under 5 minutes. In my experience, even when I'm taken to a working Nitter instance, it can get ratelimited the moment I click on any other link on the page. I could increase the querying frequency to 1 or 2 minutes, but that would likely just counterintuitively end up causing more rate limiting for Nitter instances. It's unfortunate, but there's not much I can do.
