### ISSUE TITLE
Add redlib

### ISSUE THREAD

**Issue by testman42** [benbusby/farside#169]
A fork of Libreddit that has implemented mitigations for Reddit's rate limiting
https://github.com/redlib-org/redlib

**Comment by NexusSfan** [comment]
Isn't Redlib already in farside?

**Comment by testman42** [comment]
You are correct, it was already in at the time of opening this issue.
https://github.com/benbusby/farside/blame/main/services.json#L28
And https://farside.link/libreddit redirecting to RedLib instances is also a good thing. 
:+1:
