### ISSUE TITLE
Fatal error, can't open config file '/usr/local/etc/redis.conf'

### ISSUE THREAD

**Issue by happening-primal** [benbusby/farside#17]
This is an awesome tool!

I'm trying to self host it and following the instructions, when I try to fire off the redis-server (redis-server /usr/local/etc/redis.conf) I get the above error due to the file not existing.  Maybe something simple I'm doing wrong...

Any help, much appreciated.

**Comment by benbusby** [comment]
> This is an awesome tool!

Thanks!

> I'm trying to self host it and following the instructions, when I try to fire off the redis-server (redis-server /usr/local/etc/redis.conf) I get the above error due to the file not existing. Maybe something simple I'm doing wrong...
> 
> Any help, much appreciated.

That config file actually shouldn't be needed -- I've been meaning to update the docs to reflect that. Can you try just running `redis-server` by itself (without any config path)?

**Comment by happening-primal** [comment]
> > This is an awesome tool!
> 
> Thanks!
> 
> > I'm trying to self host it and following the instructions, when I try to fire off the redis-server (redis-server /usr/local/etc/redis.conf) I get the above error due to the file not existing. Maybe something simple I'm doing wrong...
> > Any help, much appreciated.
> 
> That config file actually shouldn't be needed -- I've been meaning to update the docs to reflect that. Can you try just running `redis-server` by itself (without any config path)?

Yes, that helped, but not I am getting an error on the 'mix run -e Farside.Instances.sync' command related to poison compilation.  I am not familiar with elixir and you can imagine searching for 'elixir poison' yields some unhelpful results. :)

...==> jason
Compiling 8 files (.ex)
Generated jason app
==> poison
Compiling 4 files (.ex)
Killed

The 'mix run --no-halt' command ends with the same error.

==> poison
Compiling 4 files (.ex)
Killed

Hoping you can give me another little hint to move things along.

**Comment by benbusby** [comment]
Hmmm, that sounds like your machine might be running out of memory or something when compiling `poison`. I've noticed that library always takes a while to compile on new machines, and isn't strictly necessary for the project, so I'll look into removing that dependency.

**Comment by benbusby** [comment]
@happening-primal OK, `poison` is no longer required to build the project. Try pulling and rebuilding (potentially also removing existing build dirs like `_build` and `deps` if needed) and let me know if that fixes your problem.

**Comment by happening-primal** [comment]
> Hmmm, that sounds like your machine might be running out of memory or something when compiling `poison`. I've noticed that library always takes a while to compile on new machines, and isn't strictly necessary for the project, so I'll look into removing that dependency.

Maybe so.  When I went back through the steps you prescribed, it seemed to install poison...

**Comment by happening-primal** [comment]
> @happening-primal OK, `poison` is no longer required to build the project. Try pulling and rebuilding (potentially also removing existing build dirs like `_build` and `deps` if needed) and let me know if that fixes your problem.

Anyway, SUCCESS!!!!  Than again for your tool and for your help.

**Comment by happening-primal** [comment]
One other thing for those trying to self host this...

Instead of using the '' command, you can run this in 'daemon' mode using a slight variation 'elixir --erl "-detached"  -S mix run --no-halt' which can be run at startup.

Reference:  https://stackoverflow.com/questions/24039245/how-do-elixir-with-mix-make-a-daemon

You can check out command line switches to point to your unpacked farside instance here:  https://hexdocs.pm/mix/Mix.Tasks.Run.html

Thanks for whoogle also Ben.

Think this can be closed.
