### ISSUE TITLE
About Searx

### ISSUE THREAD

**Issue by dalf** [benbusby/farside#2]
Some information that may help:
* the raw instance list: https://github.com/searx/searx-instances/blob/master/searxinstances/instances.yml (see https://github.com/searx/searx-instances/issues )
* the content of https://searx.space/ is available in JSON: https://searx.space/data/instances.json . It can help to keep only instances with a good HTTP configuration (TLS and HTTP headers)

Most of the public instances have filtron to avoid bots (at least some). See https://github.com/searx/searx-docker/blob/master/rules.json#L2-L7

**Comment by benbusby** [comment]
Awesome, thanks @dalf. That's really helpful.
