### ISSUE TITLE
Suggestion: reuse same instance within rate-limit interval

### ISSUE THREAD

**Issue by Phantop** [benbusby/farside#20]
For something like Farside, I feel like pointing to the same instance of a given service if receiving multiple requests to that service might be a good idea. I say this partly for usage with RSS, which is a very common usecase for me with many of these services as they offer RSS where official means do not.

However, this rate limiting can often mean updating a feed may fail. I think giving the same instance again might be a good way to mitigate the chances of this happening while also still reducing the load on the Farside server some. I may be wrong, but requests being outright denied in more programmatic situations like this is a little frustrating, especially with there only being a single Farside instance.

**Comment by benbusby** [comment]
Thanks for the suggestion. It's been added and will be deployed shortly.
