### ISSUE TITLE
Support SearXNG

### ISSUE THREAD

**Issue by peepopoggers** [benbusby/farside#23]
Instances (some are SearX not searXNG): https://searx.space/

GH: https://github.com/searxng/searxng

**Comment by Mennaruuk** [comment]
All 81 instanced checked as of 3/17/2022.

| Instance                                 | URL                                         | Type                             |
|------------------------------------------|---------------------------------------------|----------------------------------|
| https://search.ononoki.org/              | https://github.com/searxng/searxng          | searxng                          |
| https://paulgo.io/                       | https://github.com/paulgoio/searxng         | searxng                          |
| https://searx.tiekoetter.com/            | https://github.com/tiekoetter/searxng       | searxng                          |
| https://searx-private-search.de/         | https://github.com/TordenskjoldJr/searxng   | searxng                          |
| https://northboot.xyz/                   | https://github.com/searxng/searxng          | searxng                          |
| https://searx.be/                        | https://github.com/searxng/searxng          | searxng                          |
| https://search.mdosch.de/                | https://github.com/searxng/searxng          | searxng                          |
| https://search.bus-hit.me/               | https://github.com/searxng/searxng          | searxng                          |
| https://s.zhaocloud.net/                 | https://github.com/searxng/searxng          | searxng                          |
| https://swag.pw/                         | https://github.com/searxng/searxng          | searxng                          |
| https://searxng.zackptg5.com/            | https://github.com/searxng/searxng          | searxng                          |
| https://serx.cf/                         | https://github.com/inoblue/searxng          | searxng                          |
| https://searx.mha.fi/                    | https://github.com/searxng/searxng          | searxng                          |
| https://searx.ebnar.xyz/                 | https://github.com/searxng/searxng          | searxng                          |
| https://searx.gnous.eu/                  | https://github.com/searxng/searxng          | searxng                          |
| https://searx.bar/                       | https://github.com/searx/searx              | searx                            |
| https://search.stinpriza.org/            | https://salsa.debian.org/debian/searx       | searx                            |
| https://search.asynchronousexchange.com/ | https://github.com/searx/searx              | searx                            |
| https://www.webrats.xyz/                 | https://github.com/theeddie/webratsxyz      | WebRats.xyz (searxng underneath) |
| https://anon.sx/                         | https://github.com/searx/searx              | searx                            |
| https://search.disroot.org/              | https://github.com/searx/searx              | searx                            |
| https://searx.fmac.xyz/                  | https://github.com/searxng/searxng          | searxng                          |
| https://searx.ru/                        | https://github.com/searx/searx              | searx                            |
| https://searx.gnu.style/                 | https://github.com/dasj19/searx             | searx                            |
| https://searx.theanonymouse.xyz/         | https://github.com/searx/searx              | searx                            |
| https://searx.prvcy.eu/                  | https://github.com/searx/searx              | searx                            |
| https://searx.webheberg.info/            | https://github.com/searx/searx              | searx                            |
| https://searx.nevrlands.de/              | https://github.com/searx/searx              | searx                            |
| https://search.jpope.org/                | https://github.com/searx/searx              | searx                            |
| https://searx.pwoss.org/                 | https://github.com/searx/searx              | searx                            |
| https://www.gruble.de/                   | https://github.com/searx/searx              | searx                            |
| https://procurx.pt/                      | https://github.com/searx/searx              | searx                            |
| https://searx.stuehieyr.com/             | https://github.com/searx/searx              | searx                            |
| https://searx.divided-by-zero.eu/        | https://github.com/searx/searx              | searx                            |
| https://search.neet.works/               | https://github.com/searxng/searxng          | searxng                          |
| https://searx.sp-codes.de/               | https://github.com/searx/searx              | searx                            |
| https://searx.xyz/                       | https://github.com/searx/searx              | searx                            |
| https://searx.rasp.fr/                   | https://github.com/searxng/searxng          | searxng                          |
| https://searx.tuxcloud.net/              | https://github.com/searx/searx              | searx                            |
| https://searx.tux.land/                  | https://github.com/searx/searx              | searx                            |
| https://searx.bissisoft.com/             | https://github.com/searx/searx              | searx                            |
| https://search.snopyta.org/              | https://github.com/searx/searx              | searx                            |
| https://searx.roflcopter.fr/             | https://github.com/searx/searx              | searx                            |
| https://searx.netzspielplatz.de/         | https://github.com/searx/searx              | searx                            |
| https://searx.dresden.network/           | https://github.com/searx/searx              | searx                            |
| https://searx.mastodontech.de/           | https://github.com/searx/searx              | searx                            |
| https://sx.catgirl.cloud/                | https://github.com/searx/searx              | searx                            |
| https://searx.solusar.de/                | https://github.com/searx/searx              | searx                            |
| https://suche.uferwerk.org/              | https://github.com/searx/searx              | searx                            |
| https://suche.tromdienste.de/            | https://github.com/searx/searx              | searx                            |
| https://search.trom.tf/                  | https://github.com/searx/searx              | searx                            |
| https://searx.zecircle.xyz/              | https://github.com/searx/searx              | searx                            |
| https://searx.run/                       | https://github.com/searx/searx              | searx                            |
| https://searx.nakhan.net/                | https://github.com/searx/searx              | searx                            |
| https://suche.dasnetzundich.de/          | https://github.com/searx/searx              | searx                            |
| https://searx.nixnet.services/           | https://github.com/searx/searx              | searx                            |
| https://searx.esmailelbob.xyz/           | https://github.com/searx/searx              | searx                            |
| https://searx.mxchange.org/              | https://github.com/searx/searx              | searx                            |
| https://search.antonkling.se/            | https://github.com/searx/searx              | searx                            |
| https://searx.josie.lol/                 | https://github.com/searx/searx              | searx                            |
| https://jsearch.pw/                      | https://github.com/searx/searx              | searx                            |
| https://engo.mint.lgbt/                  | https://github.com/searx/searx              | searx                            |
| https://search.ethibox.fr/               | https://github.com/searx/searx              | searx                            |
| https://searx.org/                       | https://github.com/searx/searx              | searx                            |
| https://searx.zapashcanon.fr/            | https://salsa.debian.org/debian/searx       | searx                            |
| https://timdor.noip.me/searx/            | https://github.com/searx/searx              | searx                            |
| https://searx.openhoofd.nl/              | https://github.com/searx/searx              | searx                            |
| https://dynabyte.ca/                     | https://github.com/searx/searx              | searx                            |
| https://searx.tyil.nl/                   | https://github.com/searx/searx              | searx                            |
| https://search.zdechov.net/              | https://salsa.debian.org/debian/searx       | searx                            |
| https://searx.roughs.ru/                 | https://github.com/searx/searx              | searx                            |
| https://searx.ninja/                     | https://github.com/searx/searx              | searx                            |
| https://trovu.komun.org/                 | https://github.com/searx/searx              | searx                            |
| https://searx.everdot.org/               | https://github.com/searx/searx              | searx                            |
| https://search.st8.at/                   | https://github.com/searx/searx              | searx                            |
| https://searx.thegreenwebfoundation.org/ | https://github.com/searx/searx              | searx                            |
| https://searx.slash-dev.de/              | https://github.com/searx/searx              | searx                            |
| https://searx.lavatech.top/              | https://github.com/searx/searx              | searx                            |
| https://darmarit.org/searx/              | https://github.com/return42/searxng         | searxng                          |
| https://nibblehole.com/                  | https://github.com/searx/searx              | searx                            |
| https://spot.ecloud.global/              | https://gitlab.e.foundation/e/cloud/my-spot | Spot (a searx fork)              |

**Comment by peepopoggers** [comment]
would be nice to choose between searx and searxng :>

**Comment by Mennaruuk** [comment]
I already made an issue over at seaxng requesting to label each instance as searx vs searxng. Once that is done, if Ben somehow finds a way to do it before searxng, I’ll make an issue over at LibRedirector to consider implementing a dropdown menu.

**Comment by peepopoggers** [comment]
depending on how the info is fetched, the html page has title attributes for each instance saying if it is searx or searxng

**Comment by Mennaruuk** [comment]
Fair enough, I checked, and indeed virtually all of them have searx or searxng in the title attributes. I let the libredirect dev about this, fingers crossed.

**Comment by benbusby** [comment]
Added support and autoupdating for SearXNG instances. Regular farside redirects for "searx" will use both SearX and SearXNG instances, while specifying "searxng" in the link will only use SearXNG instances.

**Comment by dalf** [comment]
For information : https://github.com/searxng/searxng/discussions/1046

In few hours, in addition to `version` field and the other existing fields, there will be a new `generator` field with the value of either `searx` or `searxng`.

The value comes from HTML element meta, for example:
`<meta name="generator" content="searxng/2022.03.26-1ee5cfb0">`

**Comment by Mennaruuk** [comment]
Thank you so much @dalf

**Comment by sjehuda** [comment]
Hello, I've made a Userscript for Farside.
https://github.com/benbusby/farside/issues/29

I want to add more URLs for instances of searx and SearxNG.
Can somebody please provide me with a list of searx and SearxNG instances?

Like this:
```
  site = [
    // searx
    'https://farside.link/searx',
    'https://searx.webheberg.info',
    'https://searx.tyil.nl',
    'https://searx.tuxcloud.net',
    'https://searx.tux.land',
    'https://searx.theanonymouse.xyz',
    'https://searx.stuehieyr.com',
    'https://searx.sp-codes.de',
    'https://searx.ru',
    'https://searx.rasp.fr',
    'https://searx.ninja',
    'https://searx.gnu.style',
    'https://searx.divided-by-zero.eu',
    'https://search.neet.works',
    'https://search.jpope.org',
    'https://search.asynchronousexchange.com',
    'https://procurx.pt',
    'https://dynabyte.ca',
    // searxng
    'https://farside.link/searxng',
    'https://swag.pw',
    'https://searxng.zackptg5.com',
    'https://searx.tiekoetter.com',
    'https://searx.prvcy.eu',
    'https://searx.mha.fi',
    'https://searx.jaska.cc',
    'https://searx.fmac.xyz',
    'https://searx.ebnar.xyz',
    'https://searx.be',
    'https://search.zzls.xyz',
    'https://search.vojkovic.xyz',
    'https://search.rabbit-company.com',
    'https://search.ononoki.org',
    'https://search.neet.works',
    'https://search.mdosch.de',
    'https://s.zhaocloud.net',
    'https://paulgo.io',
    'https://northboot.xyz',
    'https://etsi.me'];
```

Thank you
