### ISSUE TITLE
Whoogle language settings- keep getting German results despite '&lang_interface=en' 

### ISSUE THREAD

**Issue by atbplhy** [benbusby/farside#32]
Hi, I keep getting German results. I've added Farside as a search engine in firefox with the '&lang_interface=en' added after the search terms, however I regularly get German results, mostly from the whoogle.lunar.icu instance. 

In the address bar I get something like 'https://whoogle.lunar.icu/search?q=whatever&lang_interface=en' so it does seem to be registering it but I still get the german instance most of the time. This occurs both on android and windows firefox.

Any ideas? I can't seem to find a way to block a particular instance as a workaround either.

Thanks otherwise for a super useful tool!

**Comment by czoins** [comment]
You should use ```lang_search=en``` for search results language

**Comment by atbplhy** [comment]
Thank you!
