### ISSUE TITLE
Open up the wiki and let people contribute with simple tips and howto's

### ISSUE THREAD

**Issue by m040601** [benbusby/farside#38]
A big thanks to benbusy for this wonderfull, so much underrated, tool. Your brilliant idea, and work commited is much appreciated.

But I'm not sure, many people understand the power of this redirector thingy. And how easy it is to make use of such a tool in variety of contexts.

And even more so the latest changes, https://github.com/benbusby/farside/issues/37 , make it so much simpler to use.

I see that some people have contributed for example, with a GreaseMonkey userscript, https://github.com/benbusby/farside/issues/29. This issue was opened and closed and this "knowledge" is now "burried".

The same could be said,for example, for a couple of simple lines, instructing how to configure your OpenWrt router. Or even if a future package would be available for this router distribution.

Or "How I installed" farside in a small Raspberry Pi. 
Or how to simply configure Chrome orFirefox default seach to use a Farside link (no need for extensions).

Or a list of other future "farside instances".

Or ...
 

I would suggest the proper place to collect all these user contributed tips, would be the wiki page. And you would still maintain tight personal editing control of your README page.

**Comment by benbusby** [comment]
Just created the wiki and enabled public editing of wiki pages. Thanks for the suggestion, I think that's a great idea.

>  Or how to simply configure Chrome orFirefox default seach to use a Farside link (no need for extensions).

I actually didn't know that was possible without an extension!

**Comment by m040601** [comment]
Just to give you an example of how the public wiki might be usefull for others, I'll tell you my personal story installing Farside.

I'm not a developer or programmer. But I'm a proficient command line user. I run Archlinux and I like simplicity. I know how to install databases and run server services. But hate overengineering and complicated "homelab" and personal "infrastructure" setups. 


When I first heard of farside, just by accident, I thought: great idea ! 

And then ... but then I'll make myself dependent on this specific "farside.link" domain and this benbusy guy running it.

And then ... no ! Wait it's opensource ! I can install an instance my self.

And then, on the README ....

> 
>     Install [redis](https://redis.io/)
>     Install [elixir](https://elixir-lang.org/install.html)
>     (on Debian systems)....
> 

 Redis ? I know that. It's even officially package for Archlinux. Just a click away.

But then ... elixir ? ... mix ? What are these "things" ? Another bloated ecosystem like "npm" ? 

And erlang ? Isn't that used for big heavy iron mega services ? Am I gonna bloat and pollute my desktop trying to install this thing ?


But then, ... I took the challenge. This "Erlang" thing seems to be used by developers who know what they are doing.


A quick search in the Archlinux official package repositories and I found all I needed. Erlang, Mix, Elixir, etc.

All officially packaged. No need for building it my self. No complicated setup. And butter smooth service  startup and running, without hour long complicated editing of configuration fies. 

And there even are Archlinux wiki pages. So other Archlinux users must be using Erlang also. Great, I'm not alone.

**Comment by ltGuillaume** [comment]
> The same could be said,for example, for a couple of simple lines, instructing how to configure your OpenWrt router. Or even if a future package would be available for this router distribution.
> 
> Or "How I installed" farside in a small Raspberry Pi. Or how to simply configure Chrome orFirefox default seach to use a Farside link (no need for extensions).

Please do explain these in the new wiki, I'm intrigued!
