### ISSUE TITLE
Adding more alternatives

### ISSUE THREAD

**Issue by yshalsager** [benbusby/farside#4]
- teddit https://codeberg.org/teddit/teddit - https://teddit.net/about
> A free and open source alternative Reddit front-end focused on privacy. Inspired by the Nitter project.

- Piped https://github.com/TeamPiped/Piped - https://piped.kavin.rocks/
> An alternative privacy-friendly YouTube frontend which is efficient by design.

- SimplyTranslate https://git.sr.ht/~metalune/simplytranslate_web - https://simple-web.org/projects/simplytranslate.html
> We aim to provide fast and private translations to the user without wasting much overhead for extensive styling or JavaScript

**Comment by benbusby** [comment]
Thanks! All of have been added.
