### ISSUE TITLE
Add instance: opnxng.com

### ISSUE THREAD

**Issue by extremelyonline** [benbusby/farside#42]
Hi, great tool!

I host many instance on opnxng.com, would you consider adding them?

SearXNG
https://opnxng.com/
Whoogle
https://w.opnxng.com/
Teddit
https://i.opnxng.com/
Libreddit
https://l.opnxng.com/
Nitter
https://t.opnxng.com/
Lingva
https://lingva.opnxng.com/

**Comment by unixfox** [comment]
Add them on the corresponding list of the listed projects and they will be added on farside

**Comment by extremelyonline** [comment]
I see thank you!
