### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by McSinyx** [benbusby/farside#50]
I am interested in running a farside instance.  Without knowing any elixir, I managed to use nix's mixRelease, which gives me the following:

```console
$ tree result
result
├── bin
│   └── farside
├── erts-12.2
│   └── bin
│       └── *
├── lib
│   └── *
└── releases
    ├── 0.1.0
    │   └── *
    └── start_erl.data
$ result/bin/farside
cat: result/releases/COOKIE: No such file or directory
```

Obviously this is not right and I don't expect you to know how to do it in nix, but I'd appreciate the installation procedure so that I can bring it to the nix folks for assistance.

**Comment by benbusby** [comment]
Does [the development section of the README](https://github.com/benbusby/farside#development) cover enough info? I'm happy to expand on any of those steps if needed. There also shouldn't be a need to build/use a release version of the app -- running `mix run --no-halt` should be good enough.

**Comment by McSinyx** [comment]
I thought the development guide is for hacking and imagine
it is possible to compile farside to binaries independent of mix.

It would be more preferable for downstream/users to avoid
runtime dependencies where possible.  Therefore, I would like
to know how to correctly compile the program because it seems
mix does support that.
