### ISSUE TITLE
[Meta] Nginx HTTPS redirection not working

### ISSUE THREAD

**Issue by kubo6472** [benbusby/farside#59]
accidentally going to http results in nginx 404 error on the main instance.

something like this would probably fix it:
```yml
server {
    listen 80;
    server_name farside.link;
    return 301 https://$server_name$request_uri;
}
```

**Comment by benbusby** [comment]
Oops, I was messing around with my Nginx config and must've disabled the https redirection. Thanks -- fixed now.
