### ISSUE TITLE
Multi language issue/support 

### ISSUE THREAD

**Issue by Bkmd100** [benbusby/farside#6]
Whoogle supports changing interface and search results language through environment variable. This may cause issues as farside does not. For example using https://farside.link/whoogle/search?q=elixir you may get forwarded to https://whooglesearch.net/  that only supports **spanish** results. Here's a table of whoogle instances and their supported languages   (source: https://github.com/benbusby/whoogle-search): 
![image](https://user-images.githubusercontent.com/29681960/146688422-f7dba7b2-555a-475b-93bc-0320be99c101.png)

suggested solution: specify the desired language in the url that so it forwards the search to whoogle instances that supports that language, something like this https://farside.link/whoogle/search?language=en&q=elixir

**Comment by benbusby** [comment]
Thanks for pointing that out. I updated the readme with the `lang_interface` param set, which should work to enforce the demo language for any up-to-date Whoogle instances.
