### ISSUE TITLE
Imginn?

### ISSUE THREAD

**Issue by ltGuillaume** [benbusby/farside#61]
Every time I use farside.link/bibliogram/*, I get redirected to imginn.com. This redirection is probably done by the only Bibliogram instance left in your curated list, https://bibliogram.privacydev.net

1. What is this service?
2. Has it been vetted? There's no privacy policy, no source code, and very little information
3. There's also imginn.org, same code, different UI?

**Comment by neurodiverseEsoteric** [comment]
![RIPBibliogram_Screenshot_20220819_133955](https://user-images.githubusercontent.com/577091/185703875-bca4d58e-c89a-48a7-9b74-97e80cf46b4d.png)


>Hi everyone, I'm discontinuing Bibliogram.
>
>I'm doing this because I just don't want to work on it anymore. It's very depressing because I'm working against a hostile system and a hostile company, and not very rewarding since I do not personally care about anyone/anything on Instagram. It's a chore that Instagram is continuously and actively trying to stop me from doing. I have been thinking about this for a couple of weeks.
>
>There will maybe be one more commit for personal use and one more commit that public instances can use to display a >discontinued message and remove user lookup functionality. Bibliogram can still be used to view individual posts, which is >pretty cool, so having it as just a post viewer will be its future - until that breaks too.
>Bibliogram is still really good code to work on if anybody wants to try to fix collecting the data from Instagram. You can write a >new function (or edit an existing one) in collectors.js to make an upstream request, and then you can parse the response using >whatever you want, and return a User structure. You're welcome to maintain a fork if you fix this, but if you plan to upload your >fork to GitHub, please also edit the readme. (While you're at it, I'd suggest a name change to reduce the risks of legal action - >Bibliograph is a name that's been floating in my head for a while that you can use if you'd like.)
>
>I have not received any legal demands and there are no legal restrictions on Bibliogram or its code besides the AGPL license.
>
>It's been two and a half years. This is now a mourning chatroom. Thanks for the fun, and pour one out for Bibliogram.


Source: https://matrix.to/#/!seqaBRImHwZJpNbjYb:cadence.moe:8111/$SVA58yktA7bSubQ6L760sJwl0gpH3FkxB1BtIX4Hwi0?via=cadence.moe&via=matrix.org&via=tchncs.de

**Comment by ltGuillaume** [comment]
@neurodiverseEsoteric I forgot to state the obvious, i.e. that I'm aware of the discontinuation of Bibliogram, but that still leaves the questions posed.

**Comment by PrivacyDevel** [comment]
Hi! I am the owner of https://privacydev.net and since I discontinued to host my Bibliogram instance because of its broken state, I wanted to redirect people that still find links and have bookmarks that point to https://bibliogram.privacydev.net to another working Instagram front-end to make it as painless of a shutdown for the users as possible.

Since all Bibliogram instances are equally broken as mine was and Imginn offers a superior experience for users without an account compared to using Instagram directly, I decided to automatically redirect users to valid Imginn URLs instead.

I did ask the Bibliogram maintainer to remove my instance from the official instance list because of that a while ago as well, which they did.

I understand that this may not be the behavior that everybody expects and I apologize for any confusion. But it was an easy transitional solution that I hoped would cause as little friction as possible.

But since it is not actually a Bibliogram instance it would be best to remove my instance from the list as well.

**Comment by ltGuillaume** [comment]
@PrivacyDevel Thanks for explaining the situation. I assumed this was the case, but I'm also trying to find out if Imginn can be trusted privacy-wise.

**Comment by benbusby** [comment]
I've removed the instance, since I don't personally know anything about Imginn.

**Comment by benbusby** [comment]
That said, in light of the news of Bibliogram no longer being actively developed, I'm a bit torn on whether or not Farside should continue supporting Bibliogram redirects. I guess there's always the possibility that someone else steps up and figures out a solution to the recent changes to Instagram's user profile page. But in the meantime, anyone relying on Farside for Bibliogram redirects will probably get annoyed that all of the instances are down. Anyone have any strong thoughts one way or another?

**Comment by PrivacyDevel** [comment]
Well, considering that Bibliogram isn't working anymore for user profiles at least, I see the following possible solutions:

1. redirect them to Imginn like I do for the reasons I just mentioned
2. redirect them back to the original Instagram URL
3. remove Bibliogram redirects completely (leads to dead links)
4. only redirect non-user pages, as those actually still work sometimes
5. create an informational page with a links to the original Instagram and / or Imginn URLs

Solution 5 would probably be the cleanest solution.

**Comment by ltGuillaume** [comment]
According to the message by the dev, it still partly works (posts, not user pages), which makes it a bit more complicated.
