### ISSUE TITLE
Wiki redirector

### ISSUE THREAD

**Issue by LangLangBart** [benbusby/farside#64]
Found out about this repo from comments in a recent discussion on [HackerNews](https://news.ycombinator.com/item?id=32916318). :chart_with_upwards_trend:

### request
I would like to add the following lines to your wiki. I have successfully tested the regex on these pages, it may still need to be fine tuned for edge cases.

For ease of use,
1. Install the [Redirector](https://github.com/einaregilsson/Redirector) extension
2. Add a new entry:
  - Description: `Farside`
  - Example URL: `https://www.youtube.com/watch?v=N5dauIYZTs4`
  - Include pattern: `^(?:https?://)(?:www.|)((?:imdb|imgur|instagram|medium|odysee|quora|reddit|tiktok|translate|twitter|wikipedia|youtube).(?:com|org|google.(?:com|au|de|co)).*)`
  - Redirect to: `https://farside.link/$1`
  - Pattern type: Regular Expression

**Comment by benbusby** [comment]
Thanks, this works great!

I just added your instructions to [the wiki page here](https://github.com/benbusby/farside/wiki/Browser-Extension) -- feel free to edit it if you feel like anything needs clarification.

**Comment by tio-trom** [comment]
How would this look for search? Simply adding google into the mix won't work...

**Comment by LangLangBart** [comment]
- The regex in the wiki only works for `https://translate.google.com/`, as redirection for `https://farside.link/google.com` is not supported.
- The [GitHub -
  einaregilsson/Redirector](https://github.com/einaregilsson/Redirector#use-duckduckgocom-bangs-on-google)
  extension provides an example of redirecting Google searches to another site.
