### ISSUE TITLE
Teddit instance uses tracking JS

### ISSUE THREAD

**Issue by beardedsakimonkey** [benbusby/farside#68]
Hi, thank you for creating this tool!

Contrary to the teddit README's claim of ["No JavaScript or ads"](https://codeberg.org/teddit/teddit), I've noticed that a particular teddit instance (https://teddit.nautolan.racing/) is hitting JS resources that seems to be involved in advertisement and tracking. For instance:
 - https://d38psrni17bvxu.cloudfront.net/scripts/js3caf.js
 - https://c.parkingcrew.net/scripts/sale_form.js

These are the network requests my browser makes when going to http://ww38.teddit.nautolan.racing/  (which I was redirected to by farside):
![Screen Shot 2022-10-02 at 1 58 08 PM](https://user-images.githubusercontent.com/54521218/193476021-15873915-607f-4acd-9382-142b65b5e9c7.png)

As a result of blocking these requests, I'm left with a blank page, in which case I'll typically manually go to teddit.net instead.

I'm wondering if this instance should be removed from the services list?

Thanks!

**Comment by benbusby** [comment]
Hi, thanks for pointing this out!

Teddit instances are actually auto populated for Farside during the [nightly build](https://github.com/benbusby/farside/blob/fd0ddc573bcaa98a1a58cc7994fbaec39e3834cc/.github/workflows/update-instances.yml#L162-L173) using [this list](https://codeberg.org/teddit/teddit/raw/branch/main/instances.json), so I think the best approach would be to raise an issue with the Teddit devs to get that instance re-evaluated.

**Comment by beardedsakimonkey** [comment]
Hm, looks like that instance [was removed](https://codeberg.org/teddit/teddit/commit/e5640ef5a39476179db4cb448d78ca0fb02178bf) from teddit a couple weeks ago, but farside is still redirecting to it.  Any ideas?
Thanks

**Comment by benbusby** [comment]
Yeah there's been an issue with the nightly instance update process that I haven't had a chance to fix yet. That teddit instance has been manually removed now, so it shouldn't be a problem anymore.
