### ISSUE TITLE
New Piped instances

### ISSUE THREAD

**Issue by digitalblossom** [benbusby/farside#8]
I've noticed that farside.link/piped always directs to piped.kavin.rocks

There is two new instances, which are a little hidden in the [settings page](https://piped.kavin.rocks/preferences)

1. piped.silkky.cloud
2. piped.mutahar.rocks

**Comment by benbusby** [comment]
That's strange, piped.silkky.cloud is already in the list of piped instances, so I'm curious why that instance isn't being chosen. It could be that the Farside server is being blocked from pinging the instance. I'll look into it.

piped.mutahar.rocks has been added in 71febe3d3bcc7ac8bfc9eaf5c85414f6db29f0fe. Thanks!
