### ISSUE TITLE
quetre.odyssey346.dev has been down for a while but still not removed 

### ISSUE THREAD

**Issue by JosephTico** [benbusby/farside#98]
As the title says, the instance https://quetre.odyssey346.dev/ has been gone for a while and even returns a corresponding error message, however Farside isn’t detecting this and still including it

**Comment by benbusby** [comment]
Farside doesn't scrape any content from the actual page, so user facing error messages don't really matter. In this case, the successful `200` status code returned by that instance indicated that it was still available, when it should've either been a non-200 status or just taken down altogether.
